---
title: "Natural Hazards Technical Working Group Dashboard"
output: 
  flexdashboard::flex_dashboard:
    theme:
      bg: "#ffffff"
      fg: "#404040" 
      primary: "#0571b0"
      base_font:
        google: Prompt
      code_font:
        google: JetBrains Mono
    orientation: columns
    vertical_layout: fill
    logo: E:/Official REACH-Logo.png
---


```{r setup, include=FALSE,  results='hide', message=FALSE, warning=FALSE}
library(flexdashboard)
# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()
```

Flood Hazard
===
Column {data-width=1000 .tabset}
-----------------------------------------------------------------------

### SubBlock Level Flood Water Volume
```{r ,include=FALSE,  results='hide', message=FALSE, warning=FALSE}
library(tidyverse)
library(sf)
library(leaflet)
library(mapview)
library(RColorBrewer)

```

```{r,include=FALSE,  results='hide', message=FALSE, warning=FALSE}
camp_flood <- st_read(dsn = "E:\\NatHaz\\zonal stat layer final\\Zonal_stat_sblock_level_refactored.shp")
```


```{r,message=FALSE, warning=FALSE}

mapview(camp_flood, zcol = "Flood_Volu",
        at = c (0,5000,15000,45000,90000,227000),
        col.regions = c("#eff3ff", "#bdd7e7", "#6baed6","#3182bd","#08519c"),
        lwd = 1,
        alpha = 0.9,
        legend = TRUE,
        label = "SubBlock_N",
        layer.name = "Flood Water Volume (Cubic meters)")
```

### SubBlock Level Flood Risk Area

```{r, include=FALSE,  results='hide', message=FALSE, warning=FALSE}
camp <- st_read(dsn = "E:\\Camp Boundaries 2022\\T220130_RRC_Outline_Camp_AL1.shp")
block <- st_read(dsn = "E:\\Camp Boundaries 2022\\T220130_RRRC_Outline_Block_AL2.shp")
```

```{r}
mapview(camp,color = "red",  lwd = 3, alpha.regions =0.001, alpha = 0.9, label=camp$Camp_Name, 
   labelOptions = labelOptions(noHide = TRUE, textOnly = TRUE))+
  mapview(block,color = "black",  lwd = 1.5, alpha.regions =0.001, alpha = 0.5, label=block$Block_Let, 
   labelOptions = labelOptions(noHide = TRUE, textOnly = TRUE)) + mapview(camp_flood,
        zcol = "Shelter_Ar",
        col.regions = c("#feedde","#fdbe85","#fd8d3c","#e6550d","#a63603"),
        at = c(0,2000,4000,8000, 16000,25000),
        lwd = 1,
        color = "white",
        alpha = 0, 
        legend = TRUE, 
        label = "SubBlock_N", 
        layer.name = "Structure Exposed to Flood")
```

### SubBlock Level Flood Risk Area

```{r}
clrs <- sf.colors
#display.brewer.all(colorblindFriendly = TRUE)
mapview(camp,color = "red",  lwd = 2, alpha.regions =0, alpha = 1, label=camp$Camp_Name, 
   labelOptions = labelOptions(noHide = TRUE, textOnly = TRUE))+
mapview(camp_flood,  map.types = c("Esri.WorldImagery"), zcol = "Shelter_Ar", col.regions = RColorBrewer::brewer.pal(11, "Oranges"), alpha.regions = 1, at = c(0,2000,4000,8000,16000,25000), legend = TRUE, label = "SubBlock_N", layer.name = "Structure Exposed to Flood")
```


NASA Landslide Model
===

Wind Model
===